a=int(input("enter the first number:"))
b=int(input("enter the second number:"))
print("the addition is:",a+b)
print ("the subraction is:",a-b)
print("the multiplication is:",a*b)
print("the division is:",a/b)